name: instagram
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_storage: ^11.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/image/ic_instagram.svg
   - assets/image/instaAvatar.jpg
